# -*- coding: utf-8 -*-
"""Decisions for groups tieng_anh_thua + tieng_anh_can_xem (+ a few overrides for other groups).
Tokens of tieng_anh_can_xem not listed -> GIU (brand / model / product name).
Tuple: (hanh_dong, thay_bang, quy_tac_cum, ghi_chu)
  thay_bang   : replacement when the token stands alone ("" = keep the token)
  quy_tac_cum : 'phrase => replacement' pairs separated by ' ; ' (applied before the single-token rule)"""

T = "THAY"; C = "THEO_CUM"; X = "XEM_TAY"; G = "GIU"; H = "HANVIET"

def t(rep, note=""): return (T, rep, "", note)
def c(rules, rep="", note=""): return (C, rep, rules, note)
def x(note): return (X, "", "", note)
def g(note): return (G, "", "", note)
def h(rep, note=""): return (H, rep, "", note)

DEC = {
    # ================= tieng_anh_thua (70) =================
    "casual": t("thường ngày", "'phong cách casual' -> 'phong cách thường ngày'"),
    "hot": c("Douyin Hot Model => mẫu bán chạy trên Douyin ; Hot Model => mẫu bán chạy ; hot trend => đang thịnh hành ; hot girl => cô nàng cá tính ; hot item => sản phẩm bán chạy ; hot batch => bán sỉ chạy",
             "bán chạy", "爆款; 'cực hot' (爆火) cũng thay -> 'cực bán chạy', anh xem có muốn giữ 'hot' trong văn nói không"),
    "ins": c("ins Internet người nổi tiếng => phong cách Instagram nổi tiếng trên mạng ; ins niche => độc lạ phong cách Instagram ; phong cách ins => phong cách Instagram", "Instagram", "ins风 = phong cách Instagram"),
    "instagram": g("Tên nền tảng -> giữ (cụm hỏng 'ins Internet người nổi tiếng' xử lý ở token 'ins')"),
    "dad": c("dad shoes => giày bố ; giày dad => giày bố ; kiểu dad => kiểu giày bố", "bố", "老爹鞋; data đang có 'giày bố' 136 dòng"),
    "acid": c("Hyaluronic acid => axit hyaluronic ; Amino Acid => axit amin ; Salicylic Acid => axit salicylic ; Azelaic Acid => axit azelaic ; Tranexamic Acid => axit tranexamic", "axit", "Tiếng Việt đặt 'axit' lên trước"),
    "unisex": t("nam nữ"),
    "trend": c("hot trend => đang thịnh hành", "xu hướng"),
    "shoes": c("dad shoes => giày bố", "giày"),
    "dropshipping": t("giao hộ", "一件代发; nếu anh coi 'dropship' là thuật ngữ nghề thì đổi thành GIU"),
    "dropship": t("giao hộ", "như dropshipping"),
    "drophipping": t("giao hộ", "gõ sai của dropshipping"),
    "amino": c("Amino Acid => axit amin", "amin"),
    "mask": c("Facial mask => mặt nạ ; Sleeping Mask => mặt nạ ngủ ; Bubble Mask => mặt nạ sủi bọt ; Silk Mask => mặt nạ lụa", "mặt nạ", "Thường nằm trong cụm tiếng Anh dài -> nên dịch cả cụm"),
    "tea": c("Black Tea => trà đen ; Oolong Tea => trà ô long ; Rock Tea => trà nham ; White Tea => trà trắng ; Tea Tree => tràm trà ; Tea Cake => bánh trà", "trà"),
    "body": c("ôm body => ôm dáng", "", "Tiki có dùng 'body' (42 sp); em chỉ sửa cụm 'ôm body'"),
    "centella": c("Centella Asiatica => rau má ; Centella asiatium => rau má ; Centella Sexuegrass => rau má ; Centella Snow Grass => rau má", "rau má"),
    "asiatica": c("Centella Asiatica => rau má", ""),
    "asiatium": c("Centella asiatium => rau má", ""),
    "asiatic": c("Centella Asiatic => rau má", ""),
    "romper": t("bộ liền thân"),
    "internet": c("Internet người nổi tiếng => nổi tiếng trên mạng", "", "网红"),
    "black": c("Black Tea => trà đen ; Black Sea Salt => muối biển đen ; Black and White => đen trắng", "", "Còn lại hay là tên (Black King Kong) -> giữ"),
    "camellia": t("hoa trà"),
    "girl": c("hot girl => cô nàng cá tính", "cô gái"),
    "niche": t("độc lạ", "小众"),
    "lip": c("Lip Gloss => son bóng ; Lip Balm => son dưỡng ; Lip Glaze => son kem bóng ; Lip Mud => son bùn ; Lip Cream => son kem ; Lip Essence => tinh chất dưỡng môi ; Lip Liquid => son kem lỏng", "môi"),
    "moisturizing": c("", "dưỡng ẩm", "Hay nằm trong cụm tiếng Anh dài"),
    "new": c("New Balance => New Balance ; New York => New York ; New Start => New Start", "mới"),
    "air": c("Air Vent => cửa gió ; Air Cushion => đệm khí ; Air Force => Air Force", ""),
    "astragalus": t("hoàng kỳ"),
    "cleansing": c("", "làm sạch"),
    "set": g("Tiki dùng 'set' 197 sp (set quà, set đồ) -> coi như từ mượn"),
    "cleanser": c("", "sữa rửa mặt"),
    "little": c("", "nhỏ", "Phần lớn là tên (Little Eagle, Little Raccoon) -> chỉ dịch khi không phải tên"),
    "rose": c("Rose Black Tea => trà đen hoa hồng", "hoa hồng", "ROSE (hãng) và 'Rose Park Chae-young' giữ"),
    "facial": c("Facial mask => mặt nạ ; Facial Cleanser => sữa rửa mặt", "mặt"),
    "hydrating": c("", "cấp ẩm"),
    "series": c("full series => mọi dòng xe", "", "BMW 3/5/7 Series giữ; 'PRIUS 50 series' -> 'PRIUS dòng 50' phải đảo trật tự, sửa tay"),
    "red": c("Net Red => nổi tiếng trên mạng", "đỏ"),
    "essence": c("", "tinh chất"),
    "light": c("Free Light => Free Light ; Light Luxury => sang trọng nhẹ nhàng", "nhẹ"),
    "ice": c("Ice American => Americano đá", "băng"),
    "matte": c("", "lì"),
    "old": c("old money => old money ; Old White Tea => bạch trà lâu năm ; Old Arbor => cây cổ thụ", "lâu năm", "'old money' là trend VN dùng nguyên"),
    "preppy": t("học đường", "'phong cách preppy' -> 'phong cách học đường'"),
    "sound": g("Berlin Sound = 柏林之声, tên hãng"),
    "big": c("Big Spicy Bar => que cay lớn ; Big Red Robe => Đại Hồng Bào", "lớn", "Big Dog / Big Mac là tên -> giữ"),
    "full": c("Full HD => Full HD ; full box => nguyên thùng", "nguyên"),
    "poria": t("phục linh"),
    "silk": c("Silk Mask => mặt nạ lụa", "lụa", "Bawang Silk là tên -> giữ"),
    "spicy": c("Spicy Bar => que cay ; Spicy Strips => que cay ; Spicy Tablets => miếng cay", "cay"),
    "top": x("'Top 10 X' -> '10 X hàng đầu': phải đảo trật tự, sửa tay"),
    "water": c("Water Lily => hoa súng", "nước"),
    "beauty": c("", "làm đẹp", "Phần lớn là tên (Image Beauty, Strange Beauty) -> giữ"),
    "cream": c("Lip Cream => son kem", "kem"),
    "mist": c("", "sương"),
    "sequin": t("kim sa"),
    "sequins": t("kim sa"),
    "snack": t("đồ ăn vặt"),
    "box": c("full box => nguyên thùng ; blind box => hộp mù", "hộp"),
    "bucket": c("túi bucket => túi xô ; kiểu bucket => kiểu túi xô", "xô"),
    "gradient": t("chuyển màu"),
    "jelly": t("nhựa dẻo"),
    "mud": c("Lip Mud => son bùn", "bùn"),
    "oolong": c("Oolong Tea => trà ô long", "ô long"),
    "snail": t("ốc sên"),
    "stereo": c("3D Stereo => 3D nổi", "nổi"),
    "sweatshirt": t("áo nỉ"),
    "white": c("Black and White => đen trắng ; White Tea => trà trắng ; White Clay => bùn trắng", "trắng"),
    "cucumber": t("dưa leo"),
    "mint": c("Strawberry Mint Lip Balm => son dưỡng dâu tây bạc hà", "bạc hà"),
    "strawberry": c("Strawberry Mint Lip Balm => son dưỡng dâu tây bạc hà", "dâu tây"),

    # ================= tieng_anh_can_xem (only the non-GIU ones) =================
    "sandwich": c("Son môi Sandwich => son môi hai lớp", "", "夹心口红; 'bánh sandwich' giữ"),
    "in-ear": t("nhét tai"),
    "flyknit": t("dệt kim", "飞织"),
    "fcl": t("nguyên thùng", "整箱"),
    "mercerized": t("bóng", "丝光棉: 'cotton mercerized' -> 'cotton bóng'"),
    "mercer": t("làm bóng"),
    "chunky": c("bốt cổ ngắn chunky => bốt gót thô ; giày chunky => giày bố", "gót thô", "粗跟 / 老爹鞋"),
    "rock": c("Volcano Rock => đá núi lửa ; Rock Tea => trà nham", ""),
    "t-shirt": c("Áo T-shirt => Áo thun", "áo thun"),
    "konjac": t("khoai nưa"),
    "pull-back": t("Warrior", "回力; data đang có 3 cách: Huili 17, Warrior 9, Pull-back 12 -> em để Warrior, anh chốt"),
    "autum": t("thu", "gõ sai autumn"),
    "henry": t("Henley", "亨利领 = cổ Henley"),
    "ballet": t("ba lê"),
    "flash": x("'vải flash nano' (闪光布) không rõ"),
    "cloud": c("Túi Cloud => túi đám mây ; Cloud Clog => dép sục đám mây", "đám mây"),
    "golden": c("", "vàng"),
    "jasmine": c("Jasmine Snowflake => Phiêu Tuyết hoa nhài", "hoa nhài"),
    "satchel": t("cặp"),
    "blind": c("blind box => hộp mù", "", "盲盒"),
    "chamomile": t("cúc La Mã"),
    "double": c("Double Happiness => song hỷ", "", "Nằm trong tên sản phẩm"),
    "firming": c("", "làm săn chắc"),
    "glaze": c("Lip Glaze => son kem bóng", ""),
    "honey": c("Honey Fragrance => hương mật ong", ""),
    "jumpsuit": t("bộ liền thân"),
    "onesie": t("bộ liền thân"),
    "sea": c("Black Sea Salt => muối biển đen", ""),
    "spring": x("'Spring/West Air Travel' không rõ; 'Spring Airlines' = hãng bay Xuân Thu"),
    "yan": c("Tong Yan => trẻ hóa", "", "童颜"),
    "yinghong": h("Anh Hồng", "英红 (Anh Hồng số 9)"),
    "yingde": h("Anh Đức", "英德"),
    "zhang": c("Zhang Yuanying => Jang Won-young", "", "张元英"),
    "yuanying": c("Zhang Yuanying => Jang Won-young", ""),
    "bar": c("Spicy Bar => que cay", ""),
    "cinnamon": t("Nhục Quế", "肉桂 (giống trà)"),
    "fitted": c("ga trải giường fitted => ga bọc", "bọc"),
    "money": g("'old money' là trend VN dùng nguyên"),
    "osmanthus": t("hoa quế"),
    "phoenix": c("Phoenix Dancong => Phượng Hoàng Đơn Tùng", "Phượng Hoàng"),
    "salt": c("Black Sea Salt => muối biển đen ; Sea Salt => muối biển", "muối"),
    "berry": c("Goji berry => câu kỷ tử", ""),
    "goji": c("Goji berry => câu kỷ tử", "kỷ tử"),
    "bubble": c("Bubble Mask => mặt nạ sủi bọt", "bọt"),
    "control": c("Oil Control => kiểm soát dầu", ""),
    "crispy": c("", "giòn"),
    "crystal": c("", "pha lê"),
    "patch": c("Mask Patch => miếng dán mặt nạ", "miếng dán"),
    "patk": c("Acid Patk => axit dạng miếng dán", "miếng dán", "gõ sai của Patch"),
    "accordion": t("xếp ly", "风琴包"),
    "bud": c("Yellow Bud => Hoàng Nha", ""),
    "bud-in-bud": t("búp trong búp", "芽中芽"),
    "class": c("Class A => loại A", ""),
    "cup": c("Learning Drinking Cup => cốc tập uống", "cốc"),
    "cushion": c("Air Cushion => đệm khí", ""),
    "flagship": c("cửa hàng flagship => cửa hàng chính hãng", "chính hãng"),
    "grass": c("Resurrection Grass => cỏ phục sinh ; Snow Grass => rau má", ""),
    "resurrection": c("Resurrection Grass => cỏ phục sinh", ""),
    "iceland": t("Băng Đảo", "冰岛 = làng trà Băng Đảo (Vân Nam), máy dịch nhầm thành nước Iceland"),
    "kiss": g("Kiss Stick, Honey Kiss là tên sản phẩm"),
    "off": c("90% off => giảm 90% ; 70% off => giảm 70%", ""),
    "ophiopogon": c("Ophiopogon japonicus => mạch môn", "mạch môn"),
    "japonicus": c("Ophiopogon japonicus => mạch môn", ""),
    "polygonatum": c("Polygonatum odoratum => ngọc trúc ; Polygonatum odorifera => ngọc trúc", "hoàng tinh"),
    "odoratum": c("Polygonatum odoratum => ngọc trúc", ""),
    "odorifera": c("Polygonatum odorifera => ngọc trúc", ""),
    "plant": c("", "thực vật"),
    "plasticine": t("đất nặn"),
    "platform": t("độn", "'đế xuồng platform' -> 'đế xuồng độn'"),
    "presbyopic": t("họa tiết monogram", "老花 = họa tiết monogram (LV), máy dịch thành 'lão thị'"),
    "schoolbag": t("cặp sách"),
    "spot": t("có sẵn", "现货"),
    "star": g("R Star là tên sản phẩm"),
    "sucrose": t("đường", "'0 sucrose' -> '0 đường'"),
    "wang": c("Wang Yibo => Vương Nhất Bác ; Wang Jiaer => Vương Gia Nhĩ", ""),
    "jiaer": c("Wang Jiaer => Vương Gia Nhĩ", ""),
    "authentic": c("", "chính gốc"),
    "brightening": c("", "làm sáng"),
    "cross-border": t("xuyên biên giới"),
    "fat": c("Fat Donglai => Bàn Đông Lai ; Fat Dahai => bàng đại hải", "", "胖东来 / 胖大海"),
    "fei": c("Dai Fei => Công nương Diana", "", "戴妃包"),
    "gypsophila": t("hoa baby", "满天星"),
    "kidsren": x("'3 kidsren 5' câu bị hỏng"),
    "lily": c("Water Lily => hoa súng", "hoa huệ"),
    "lychee": t("vân sần", "荔枝纹"),
    "litchi": t("vân sần", "荔枝纹"),
    "men's": c("", "nam"),
    "mirror": c("Mirror Lip Gloss => son bóng gương", "gương"),
    "night": c("Stay Up Night Mask => mặt nạ thức khuya", "đêm"),
    "purifying": c("", "làm sạch"),
    "refreshing": c("", "sảng khoái"),
    "rhinestone": t("đá", "'rhinestone trang trí' -> 'đính đá'"),
    "sleeping": c("Sleeping Mask => mặt nạ ngủ", "ngủ"),
    "snow": c("Snow Grass => rau má", "tuyết"),
    "stripesd": t("kẻ sọc"),
    "tie-dye": t("loang màu"),
    "tube": c("White Tube => tuýp trắng", "tuýp"),
    "xiao": c("Naruto Xiao => Akatsuki (Naruto)", "", "晓组织"),
    "ya'an": h("Nhã An", "雅安"),
    "yaan": h("Nhã An", "雅安"),
    "zhao": c("Zhao Lusi => Triệu Lộ Tư", ""),
    "aerobic": t("thoáng khí", "有氧纱"),
    "catty": t("cân", "斤; 'nửa catty' -> 'nửa cân'"),
    "cistanche": c("Cistanche deserticola => nhục thung dung", "nhục thung dung"),
    "deserticola": c("Cistanche deserticola => nhục thung dung", ""),
    "clip-on": t("kẹp tai"),
    "dian": h("Điền", "滇"),
    "dragon": c("Dragon and Phoenix Tea Cake => bánh trà Long Phụng", ""),
    "freeze-dried": t("đông khô"),
    "gardenia": t("hoa dành dành"),
    "general": c("General Trade => hàng thông thường", "", "一般贸易"),
    "trade": c("General Trade => hàng thông thường", ""),
    "guo": c("Luo Han Guo => la hán quả", ""),
    "luo": c("Luo Han Guo => la hán quả", ""),
    "houndstooth": t("răng sói", "千鸟格 = kẻ răng sói"),
    "k-phong": c("K-Phong Cách => phong cách Hàn Quốc", ""),
    "k-style": t("phong cách Hàn Quốc"),
    "liquid": c("Lip Liquid => son kem lỏng ; Liquid Ammonia => amoniac lỏng", ""),
    "muscle": c("Baby Muscle => da em bé", "", "婴儿肌"),
    "narcissus": t("Thủy Tiên", "水仙 (giống trà)"),
    "niang": c("Xuemei Niang => Tuyết Mị Nương", ""),
    "peel-off": c("dạng peel-off => dạng lột", "lột"),
    "perilla": t("tía tô"),
    "ping": c("Ping An => Bình An", ""),
    "pingyin": h("Bình Âm", "平阴"),
    "rejuvenating": c("", "trẻ hóa"),
    "repair": c("", "phục hồi"),
    "ribbon": c("Net Red Ribbon => ruy băng nổi tiếng trên mạng", "ruy băng"),
    "scrub": c("", "tẩy tế bào chết"),
    "seersucker": t("vải sần"),
    "sexuegrass": c("Centella Sexuegrass => rau má", "rau má"),
    "shiitake": c("nấm shiitake => nấm hương", ""),
    "shou": c("Lao Shou Gong Mei => Lão Thọ Cống Mi", ""),
    "slip-on": t("lười", "'Giày Slip-on' -> 'giày lười'"),
    "solona": t("Sorona", "索罗娜, gõ sai"),
    "sonra": t("Sorona", "索罗那, gõ sai"),
    "tree": c("Tea Tree => tràm trà", ""),
    "walfag": t("waffle", "华夫格"),
    "huafag": t("waffle", "华夫格"),
    "huafger": t("waffle", "华夫格"),
    "walfager": t("waffle", "华夫格"),
    "a-gan": t("Forrest Gump", "阿甘鞋"),
    "ammonia": c("Liquid Ammonia => amoniac lỏng", "amoniac"),
    "amping": t("ampoule", "gõ sai"),
    "ampoution": t("ampoule", "gõ sai"),
    "ball": c("Flower Ball => viên hoa", ""),
    "barbarum": c("Lycium barbarum => câu kỷ tử", ""),
    "lycium": c("Lycium barbarum => câu kỷ tử", ""),
    "bing": c("Bing Dao => Băng Đảo", ""),
    "brew": c("Cold Brew => ủ lạnh", ""),
    "cold": c("Cold Brew => ủ lạnh", ""),
    "business": c("business casual => công sở thanh lịch", ""),
    "cassia": t("thảo quyết minh", "决明子"),
    "chasing": c("Casual Chasing Drama => khi xem phim", ""),
    "drama": c("Casual Chasing Drama => khi xem phim", ""),
    "chive": t("hành lá"),
    "copper": c("Blue Copper Peptide => peptide đồng xanh", ""),
    "english": c("English series => dòng tiếng Anh", ""),
    "fan": c("nữ thần Fan => phong cách nữ thần", "", "女神范"),
    "fart": x("'túi gấu fart' không rõ"),
    "film": x("'Green Film Yellow Film' (绿膜黄膜) = mặt nạ xanh / vàng?"),
    "fragrant": c("Luzhou Fragrant Tea => trà hương đậm", ""),
    "ganoderma": c("Ganoderma lucidum => linh chi", "linh chi"),
    "lucidum": c("Ganoderma lucidum => linh chi", ""),
    "gift": c("Gift Pack => gói quà", "quà"),
    "gorgon": t("khiếm thực", "芡实"),
    "guan": c("Longmu Guan => Đồng Mộc Quan", ""),
    "gyro": t("con quay"),
    "halter": t("yếm", "'cổ halter' -> 'cổ yếm'"),
    "ice-feel": t("mát lạnh", "冰感"),
    "jerry": t("Jieli", "杰里 = chip Jieli, máy dịch thành 'Jerry'"),
    "lo-mei": t("đồ kho", "卤味"),
    "melard": t("Maillard", "美拉德"),
    "messenger": t("đưa thư", "邮差包"),
    "miscellaneous": t("đồ lặt vặt"),
    "modar": t("modal", "gõ sai"),
    "national": c("National Cosmetic => mỹ phẩm đặc trị", ""),
    "needle": c("Silver Needle => Ngân Châm", ""),
    "net": c("Net Red => nổi tiếng trên mạng", ""),
    "pastoral": c("Ins Pastoral => phong cách đồng quê", "đồng quê"),
    "pekoe": c("trắng pekoe => Bạch Hào", "Bạch Hào"),
    "peony": c("White Peony => Bạch Mẫu Đơn ; Peony Flower Ball => viên hoa mẫu đơn", "mẫu đơn"),
    "pomegranate": t("lựu"),
    "pound": t("cân", "半斤 -> nửa cân"),
    "rainbow": t("cầu vồng"),
    "rider": x("'camera mang đi xe Rider' không rõ"),
    "seaweed": t("rong biển"),
    "shikoniamide": x("Có thể là 'Shihou (施逅) niacinamide' bị dính"),
    "shiburotide": x("Có thể là 'Shihou (施逅) oligopeptide' bị dính"),
    "shit": c("Vịt Shit => Áp Thỉ Hương", "", "鸭屎香"),
    "shot": c("Real shot => ảnh thật", ""),
    "sippy": c("sippy cốc => cốc tập uống", ""),
    "small": c("Small Reservoir Mask => mặt nạ hồ chứa nhỏ", "nhỏ"),
    "soothing": c("", "làm dịu"),
    "stay": c("Stay Up Night Mask => mặt nạ thức khuya ; Stay Up Late Mask => mặt nạ thức khuya", ""),
    "strips": c("Spicy Strips => que cay", ""),
    "style": c("Ins Style => phong cách Instagram", "phong cách"),
    "swiss": t("Thụy Sĩ"),
    "tablets": c("Spicy Tablets => miếng cay", ""),
    "tambourine": t("trống lắc tay"),
    "tinkerbell": t("Doraemon", "小叮当 = Doraemon, máy dịch thành Tinkerbell"),
    "tremella": t("nấm tuyết"),
    "trendy": t("sưu tầm", "潮玩 = đồ chơi sưu tầm"),
    "tuckahoe": t("phục linh"),
    "volcano": c("Volcano Mineral => khoáng núi lửa ; Volcano Rock => đá núi lửa", "núi lửa"),
    "volcanic": c("Volcanic Mud => bùn núi lửa", "núi lửa"),
    "water-glow": t("căng bóng", "水光"),
    "water-glowing": t("căng bóng", "水光"),
    "water-glossy": t("căng bóng", "水漾"),
    "wolfberry": t("kỷ tử"),
    "xie": c("Que Xie => Tước Thiệt", ""),
    "she": c("Que She => Tước Thiệt", ""),
    "tuo": c("Que Tuo => Tước Thiệt", ""),
    "yin": c("Tie Guan Yin => Thiết Quan Âm", ""),
    "tie": c("Tie Guan Yin => Thiết Quan Âm", ""),
    "zhong": c("Xiao Zhong => Tiểu Chủng", ""),
    "akita": t("Bồ Điền", "莆田 bị dịch thành 'Akita' (dòng 'Giày Akita Dexun')"),
    "ancient": c("Spring Tree Ancient Tea => trà cổ thụ xuân", ""),
    "arbor": c("Old Arbor => cây cổ thụ", ""),
    "arc": c("Arc de Triomphe => Khải Hoàn Môn", ""),
    "triomphe": c("Arc de Triomphe => Khải Hoàn Môn", ""),
    "auspicious": c("Auspicious Xiaoyu => Cát Tường Tiểu Ngư", "", "吉祥小鱼"),
    "avat": x("'xin Avat' = 安怡 bị dịch hỏng"),
    "azulic": t("azelaic", "壬二酸"),
    "nonaitic": t("azelaic", "壬二酸"),
    "bacchus": t("Dionysus", "酒神包; thống nhất với dòng ghi 'túi Dionysus'"),
    "balm": c("Lip Balm => son dưỡng", ""),
    "batch": c("hot batch => bán sỉ chạy", ""),
    "beaver": t("hải ly"),
    "blueberry": t("việt quất"),
    "bouncy": t("nảy", "'Bóng Bouncy' -> 'bóng nảy'"),
    "burberry": t("Babani", "柏贝妮 = Babani, máy dịch nhầm thành Burberry"),
    "cao-top": t("cổ cao", "高帮"),
    "caterpillar": t("con sâu", "毛毛虫"),
    "chanel-phong": c("Chanel-Phong Cách => phong cách Chanel", ""),
    "chenier": t("chenille", "雪尼尔"),
    "xuenier": t("chenille", "雪尼尔"),
    "chlorophyll": t("diệp lục"),
    "chong'an": h("Sùng An", "崇安"),
    "clamshell": t("nắp gập"),
    "classy": t("sang trọng"),
    "clay": c("White Clay => bùn trắng", "bùn"),
    "coix": t("ý dĩ"),
    "colloidal": c("Lưu Huỳnh Colloidal => lưu huỳnh dạng keo", "dạng keo"),
    "composite": t("hỗn hợp"),
    "cork": t("bần", "软木"),
    "cornus": c("Cornus officinalis => sơn thù du", ""),
    "officinalis": c("Cornus officinalis => sơn thù du", ""),
    "cotton-linen": t("cotton-lanh"),
    "crackers": c("Tôm Crackers => snack tôm", ""),
    "cranberry": t("nam việt quất"),
    "croissant": t("bánh sừng bò"),
    "cuscuta": c("Wild Cuscuta => thỏ ty tử", "thỏ ty tử"),
    "cut-out": t("khoét"),
    "cv": x("'CV bộ váy' = OL套装裙 -> 'bộ váy công sở'?"),
    "cynomorium": t("tỏa dương"),
    "dandelion": t("bồ công anh"),
    "delicatessen": t("đồ ăn chín"),
    "distressed": c("washed distressed => wash làm cũ", "làm cũ"),
    "washed": c("washed distressed => wash làm cũ", ""),
    "donkey": x("驴 là tiếng lóng chỉ LV; 'Ba lô Donkey' = ba lô kiểu LV?"),
    "doting": t("Động Đình", "洞庭 bị phiên sai"),
    "drapey": t("rũ", "垂坠感"),
    "ear-hanging": t("đeo tai"),
    "egg": c("Egg Roll King => vua bánh cuộn trứng", ""),
    "epimedium": t("dâm dương hoắc"),
    "er": c("Er Ye Maofeng => Nhị Diệp Mao Phong", ""),
    "ye": c("Er Ye Maofeng => Nhị Diệp Mao Phong", ""),
    "eucommia": t("đỗ trọng"),
    "fantasy": t("huyền ảo"),
    "feng": c("Mao Feng => Mao Phong", ""),
    "fiber": c("carbon fiber => sợi carbon", "sợi"),
    "five": c("Five Treasures => ngũ bảo", ""),
    "treasures": c("Five Treasures => ngũ bảo", ""),
    "flip": c("iPhone 15 Flip => iPhone 15 nắp gập", "nắp gập"),
    "flip-top": t("nắp lật"),
    "gravity": c("Zero Gravity => không trọng lực", ""),
    "gynostemma": c("Gynostemma pentaphyllum => giảo cổ lam", "giảo cổ lam"),
    "pentaphyllum": c("Gynostemma pentaphyllum => giảo cổ lam", ""),
    "hamster": t("đập chuột", "打地鼠 = trò đập chuột"),
    "happiness": c("Double Happiness => song hỷ", ""),
    "harbin": h("Cáp Nhĩ Tân", "哈尔滨"),
    "hazelnut": t("hạt phỉ"),
    "hidden": t("ẩn"),
    "high": c("High Mountain Cloud Mist => Cao Sơn Vân Vụ", ""),
    "huo": c("Huo Kui => Hầu Khôi", ""),
    "ins-style": t("phong cách Instagram"),
    "item": c("hot item => sản phẩm bán chạy", ""),
    "jixuegrass": t("rau má", "积雪草"),
    "seedling": t("rau má", "积雪草 bị dịch thành 'Seedling'"),
    "kosa": t("Tiểu Chủng", "小种 bị phiên hỏng ('Zhengshan Kosa')"),
    "lactourate": t("lactobionic", "乳糖酸, gõ sai"),
    "ladiesshandbag": t("túi xách nữ"),
    "lanxess": t("Lenzing", "兰精 = Lenzing, không phải hãng hóa chất Lanxess"),
    "lesser": t("Lyocell", "莱赛尔"),
    "lycel": t("Lyocell", "莱赛尔"),
    "lycell": t("Lyocell", "莱赛尔"),
    "leap": x("'giày tháng Leap' không rõ"),
    "lofoo": t("loafer", "乐福鞋"),
    "long-staple": t("sợi dài", "'Long-Staple Cotton' -> 'cotton sợi dài'"),
    "loquat": t("tỳ bà"),
    "lu'an": h("Lục An", "六安"),
    "luan": h("Lục An", "六安"),
    "luxury": c("Light Luxury => sang trọng nhẹ nhàng", ""),
    "macadamia": t("mắc ca"),
    "mandarin": c("Chenpi Mandarin => trần bì", "quýt"),
    "marine": c("Marine Collagen => collagen biển", "biển"),
    "maryzhen": t("Mary Jane", "玛丽珍"),
    "masson": x("'abya Masson' = 亚马逊 (Amazon) bị dịch hỏng"),
    "masturbator": t("dụng cụ thủ dâm", "Sản phẩm người lớn, giữ dòng hay bỏ tuỳ anh"),
    "matsutake": t("tùng nhung", "松茸"),
    "microphone": t("micro"),
    "mmi": t("momme", "姆米 (đơn vị lụa)"),
    "monk": c("Tang Monk => Đường Tăng", ""),
    "muller": t("mule", "穆勒鞋"),
    "navigator": t("định vị"),
    "no-rinse": t("không cần rửa"),
    "noble": c("Noble Lady => quý phu nhân", "", "贵妇"),
    "nordic": t("Bắc Âu"),
    "scandinavia": t("Bắc Âu"),
    "scandinavian": t("Bắc Âu"),
    "nostalgia": t("hoài cổ"),
    "obsidian": t("hắc diện thạch", "黑曜石"),
    "over-ear": t("móc tai", "挂耳式"),
    "pistachio": t("hạt dẻ cười"),
    "plush": x("Cả cụm 'National Treasure Red Panda Plush Blind Box' cần dịch lại"),
    "pond": c("Mint Pond => Bạc Hà Đường", "", "薄荷塘"),
    "pre-rain": t("Vũ Tiền", "雨前"),
    "propolis": t("keo ong"),
    "prunella": c("Prunella Vulgaris => hạ khô thảo", ""),
    "vulgaris": c("Prunella Vulgaris => hạ khô thảo", ""),
    "quack": x("嘎嘎好穿 = 'cực dễ mang'"),
    "raw": c("Raw Tea Cake => bánh trà sống", ""),
    "relief": x("'2025 Relief' (救济) không rõ"),
    "replacement": c("", "hàng thay thế", "平替"),
    "ripe": c("Pu'er Ripe => Phổ Nhĩ chín", ""),
    "robe": c("Big Red Robe => Đại Hồng Bào", ""),
    "rou": c("Rou Gui => Nhục Quế", ""),
    "ruffle": t("bèo nhún"),
    "woodruff": t("bèo", "木耳边 bị dịch thành 'Woodruff'"),
    "sand": c("Magic Sand => cát ma thuật", ""),
    "saw": x("'Saw Duozi' = 锯朵仔 (giống trà Đơn Tùng)"),
    "scallion": t("hành lá"),
    "seasons": c("Four Seasons Pure Cotton => cotton bốn mùa", ""),
    "shan": t("Sam's", "山姆 bị dịch thành 'Shan'"),
    "shawn": c("Shawn Yue => Dư Văn Lạc", "", "余文乐"),
    "yue": c("Shawn Yue => Dư Văn Lạc", ""),
    "sheng": c("Sheng Pu => Phổ Nhĩ sống", ""),
    "sister": c("Sweet Little Sister => em gái ngọt ngào", ""),
    "sisters": c("@Sisters => các chị em", ""),
    "snake": c("Snake Venom Peptide => peptide nọc rắn", ""),
    "venom": c("Snake Venom Peptide => peptide nọc rắn", ""),
    "snowflake": c("Jasmine Snowflake => Phiêu Tuyết hoa nhài", ""),
    "soba": t("kiều mạch"),
    "spliced": t("phối"),
    "stream": t("truyền phát", "流媒体"),
    "sulfur": t("lưu huỳnh"),
    "suspottomer": x("Từ bị dịch hỏng"),
    "sydney": t("lê tuyết", "雪梨 = lê tuyết, máy dịch thành thành phố Sydney"),
    "taitws": t("tai TWS", "thiếu dấu cách"),
    "thaotws": t("thao TWS", "thiếu dấu cách ('thể thaoTWS')"),
    "tip": t("đầu", "芽尖 -> 'nụ đầu'"),
    "tou": c("Ma Tou Yan => Mã Đầu Nham", ""),
    "tour": c("tự lái tour => du lịch tự lái", ""),
    "tripe": c("Tripe Konjac => lá sách konjac", "lá sách"),
    "ttouming": t("trong suốt", "T透明"),
    "twill": t("vân chéo", "斜纹"),
    "ty-c": t("Type-C", "gõ sai"),
    "ultra-clear": t("siêu nét"),
    "verbena": t("cỏ roi ngựa"),
    "walnut": t("óc chó"),
    "wasteland": t("hậu tận thế", "废土风"),
    "wind": c("Ins Wind => phong cách Instagram", "", "风 bị dịch thành 'Wind'"),
    "yinzhen": h("Ngân Châm", "银针"),
    "latinh": g("Tiếng Việt ('Mỹ Latinh')"),
    "tens": x("'vỏ chăn TENS lụa' không rõ"),
    "voy": x("Từ bị dịch hỏng ('Ru voy Nga')"),
    "outfit": c("", "trang phục"),
}

# Overrides for tokens that live in other groups
OVERRIDE = {
    "huili": ("GIU", "", "", "回力: cùng hãng với Warrior / Pull-back; data có 3 cách viết, anh chốt 1 cách"),
    "apple": ("GIU", "", "", "Đa số là hãng Apple; 2 dòng 苹果 = quả táo (đồ trang trí, hộp hình táo) cần sửa tay"),
}
