# -*- coding: utf-8 -*-
"""Decisions for group phien_am_pinyin. Anything not listed here -> GIU (brand name kept as pinyin).
Format: token: (hanh_dong, thay_bang, ghi_chu)
  HANVIET  : place / tea / generic Chinese term -> Sino-Vietnamese reading
  THAY     : not a proper noun at all (MT left a common word as pinyin / English) -> Vietnamese word
  THEO_CUM : only correct as part of a multi-word name, see quy_tac_cum
  XEM_TAY  : could not decide from the data"""

H = "HANVIET"; T = "THAY"; C = "THEO_CUM"; X = "XEM_TAY"; G = "GIU"

DEC = {
    # ---- tea names, tea regions, places -> Hán Việt
    "huaqiangbei": (H, "Hoa Cường Bắc", "华强北, chợ điện tử Thâm Quyến"),
    "pu'er": (H, "Phổ Nhĩ", "普洱"),
    "dahongpao": (H, "Đại Hồng Bào", "大红袍"),
    "wuyishan": (H, "Vũ Di Sơn", "武夷山"),
    "wuyi": (H, "Vũ Di", "武夷"),
    "jinjunmei": (H, "Kim Tuấn Mi", "金骏眉"),
    "junmei": (H, "Tuấn Mi", "骏眉; đi sau 'Jin' thì cả cụm = Kim Tuấn Mi"),
    "zhengshan": (H, "Chính Sơn", "正山 (Chính Sơn Tiểu Chủng)"),
    "xiaozhong": (H, "Tiểu Chủng", "小种"),
    "tieguanyin": (H, "Thiết Quan Âm", "铁观音"),
    "anyang": (H, "An Dương", "安阳"),
    "biluochun": (H, "Bích Loa Xuân", "碧螺春"),
    "maojian": (H, "Mao Tiêm", "毛尖"),
    "anxi": (H, "An Khê", "安溪"),
    "putian": (H, "Bồ Điền", "莆田 (bản báo cáo trước ghi nhầm 'Phủ Điền')"),
    "nantong": (H, "Nam Thông", "南通"),
    "hengxian": (H, "Hoành Huyện", "横县"),
    "mingqian": (H, "Minh Tiền", "明前 (hái trước Thanh Minh)"),
    "qizi": (H, "Thất Tử", "七子 (bánh trà Thất Tử / Thất Tử Bạch)"),
    "tongmuguan": (H, "Đồng Mộc Quan", "桐木关"),
    "tongmu": (H, "Đồng Mộc", "桐木"),
    "fuding": (H, "Phúc Đỉnh", "福鼎"),
    "shoumei": (H, "Thọ Mi", "寿眉"),
    "laoshoumei": (H, "Lão Thọ Mi", "老寿眉"),
    "gongmei": (H, "Cống Mi", "贡眉"),
    "menghai": (H, "Mãnh Hải", "勐海"),
    "banzhang": (H, "Ban Chương", "班章"),
    "dianhong": (H, "Điền Hồng", "滇红"),
    "piaoxue": (H, "Phiêu Tuyết", "飘雪"),
    "xinhui": (H, "Tân Hội", "新会"),
    "fengqing": (H, "Phượng Khánh", "凤庆"),
    "zhengyan": (H, "Chính Nham", "正岩"),
    "anji": (H, "An Cát", "安吉"),
    "dancong": (H, "Đơn Tùng", "单丛/单枞"),
    "maofeng": (H, "Mao Phong", "毛峰"),
    "daliangshan": (H, "Đại Lương Sơn", "大凉山"),
    "longjing": (H, "Long Tỉnh", "龙井"),
    "xiaoqinggan": (H, "Tiểu Thanh Cam", "小青柑"),
    "xiaoqingkan": (H, "Tiểu Thanh Cam", "小青柑 (phiên sai)"),
    "xiaoqing": (H, "Tiểu Thanh", "小青 ('Xiaoqing Orange' = cam Tiểu Thanh)"),
    "xinyang": (H, "Tín Dương", "信阳"),
    "qimen": (H, "Kỳ Môn", "祁门"),
    "qihong": (H, "Kỳ Hồng", "祁红"),
    "fujian": (H, "Phúc Kiến", "福建"),
    "longzhu": (H, "Long Châu", "龙珠"),
    "songyang": (H, "Tùng Dương", "松阳"),
    "taiping": (H, "Thái Bình", "太平"),
    "xiaotuo": (H, "Tiểu Đà", "小沱"),
    "xiaojintuo": (H, "Tiểu Kim Đà", "小金沱"),
    "tuocha": (H, "Đà Trà", "沱茶"),
    "xinjiang": (H, "Tân Cương", "新疆"),
    "yunnan": (H, "Vân Nam", "云南"),
    "chenpi": (H, "trần bì", "陈皮 (vỏ quýt khô)"),
    "enshi": (H, "Ân Thi", "恩施"),
    "gongfu": (H, "Công Phu", "工夫"),
    "houkui": (H, "Hầu Khôi", "猴魁"),
    "lincang": (H, "Lâm Thương", "临沧"),
    "pinghu": (H, "Bình Hồ", "平湖"),
    "yashixiang": (H, "Áp Thỉ Hương", "鸭屎香"),
    "zhangjiajie": (H, "Trương Gia Giới", "张家界"),
    "anhua": (H, "An Hóa", "安化"),
    "bitan": (H, "Bích Đàm", "碧潭"),
    "bozhou": (H, "Bạc Châu", "亳州"),
    "dafo": (H, "Đại Phật", "大佛"),
    "dafu": (H, "Đại Phật", "大佛 (phiên sai)"),
    "dayuling": (H, "Đại Vũ Lĩnh", "大禹岭"),
    "huangya": (H, "Hoàng Nha", "黄芽"),
    "hunan": (H, "Hồ Nam", "湖南"),
    "jiangshan": (H, "Giang Sơn", "江山; 'Qianli Jiangshan' = Thiên Lý Giang Sơn"),
    "qianli": (H, "Thiên Lý", "千里; 'Qianli Jiangshan' = Thiên Lý Giang Sơn"),
    "rizhao": (H, "Nhật Chiếu", "日照"),
    "rougui": (H, "Nhục Quế", "肉桂"),
    "taizhou": (H, "Thai Châu", "台州"),
    "tianjian": (H, "Thiên Tiêm", "天尖"),
    "tujia": (H, "Thổ Gia", "土家"),
    "xuemei": (H, "Tuyết Mị", "雪媚; 'Xuemei Niang' = Tuyết Mị Nương"),
    "xuemeiniang": (H, "Tuyết Mị Nương", "雪媚娘"),
    "yongshun": (H, "Vĩnh Thuận", "永顺"),
    "alishan": (H, "A Lý Sơn", "阿里山"),
    "baihao": (H, "Bạch Hào", "白毫"),
    "banna": (H, "Bản Nạp", "版纳"),
    "xishuangbanna": (H, "Tây Song Bản Nạp", "西双版纳"),
    "bingdao": (H, "Băng Đảo", "冰岛"),
    "bujian": (H, "Bố Tiêm", "布尖"),
    "chenxiang": (H, "Trần Hương", "陈香"),
    "dongting": (H, "Động Đình", "洞庭"),
    "fuxing": (H, "Phục Hưng", "复兴 (tàu cao tốc)"),
    "guapian": (H, "Qua Phiến", "瓜片"),
    "huangshan": (H, "Hoàng Sơn", "黄山"),
    "jinluo": (H, "Kim Loa", "金螺"),
    "liubao": (H, "Lục Bảo", "六堡"),
    "longyan": (H, "Long Nham", "龙岩"),
    "meitan": (H, "Mi Đàm", "湄潭"),
    "pingjiang": (H, "Bình Giang", "平江"),
    "qilan": (H, "Kỳ Lan", "奇兰"),
    "quanzhou": (H, "Tuyền Châu", "泉州"),
    "wenzhou": (H, "Ôn Châu", "温州"),
    "wudong": (H, "Ô Đông", "乌岽"),
    "yiwu": (H, "易武→Dịch Vũ | 义乌→Nghĩa Ô", "Tuỳ chữ Hán trong title_zh của từng dòng"),
    "baigou": (H, "Bạch Câu", "白沟"),
    "changsha": (H, "Trường Sa", "长沙"),
    "chaozhou": (H, "Triều Châu", "潮州"),
    "chigan": (H, "Xích Cam", "赤甘"),
    "cuiya": (H, "Thúy Nha", "翠芽"),
    "dajinzhen": (H, "Đại Kim Châm", "大金针"),
    "fuzhuan": (H, "Phục Chuyên", "茯砖 (trà gạch)"),
    "ganlishan": (H, "Cam Lê Sơn", "甘梨山"),
    "guizhou": (H, "Quý Châu", "贵州"),
    "huidong": (H, "Huệ Đông", "惠东"),
    "huzhou": (H, "Hồ Châu", "湖州"),
    "jiaxing": (H, "Gia Hưng", "嘉兴"),
    "jingmai": (H, "Cảnh Mại", "景迈"),
    "jinjiang": (H, "Tấn Giang", "晋江"),
    "laifeng": (H, "Lai Phượng", "来凤"),
    "laocong": (H, "Lão Tùng", "老枞"),
    "laozhai": (H, "Lão Trại", "老寨"),
    "lanxiang": (H, "Lan Hương", "兰香"),
    "longxu": (H, "Long Tu", "龙须"),
    "lushan": (H, "Lư Sơn", "庐山"),
    "maotouyan": (H, "Mã Đầu Nham", "马头岩 (phiên sai)"),
    "matouyan": (H, "Mã Đầu Nham", "马头岩"),
    "minbei": (H, "Mân Bắc", "闽北"),
    "mengding": (H, "Mông Đỉnh", "蒙顶"),
    "nanjing": (H, "Nam Kinh", "南京"),
    "pingxiang": (H, "Bình Hương", "萍乡"),
    "qingming": (H, "Thanh Minh", "清明"),
    "queshe": (H, "Tước Thiệt", "雀舌"),
    "qixi": (H, "Thất Tịch", "七夕"),
    "shanmingqian": (H, "Sơn Minh Tiền", "山明前"),
    "shanyan": (H, "Sơn Nham", "山岩"),
    "shimen": (H, "Thạch Môn", "石门"),
    "shuixian": (H, "Thủy Tiên", "水仙 (giống trà)"),
    "sichuan": (H, "Tứ Xuyên", "四川"),
    "tongmuguan_": (H, "", ""),
    "weihai": (H, "Uy Hải", "威海"),
    "wuxi": (H, "Vô Tích", "无锡"),
    "wuzhai": (H, "Ngũ Trại", "五寨"),
    "xiangluo": (H, "Hương Loa", "香螺"),
    "xiaoye": (H, "Tiểu Diệp", "小叶"),
    "xihu": (H, "Tây Hồ", "西湖"),
    "xinchang": (H, "Tân Xương", "新昌"),
    "xuezhu": (H, "Tuyết Trúc", "雪竹"),
    "yanbian": (H, "Diên Biên", "延边"),
    "yangjiang": (H, "Dương Giang", "阳江"),
    "yiyang": (H, "Ích Dương", "益阳"),
    "yulu": (H, "Ngọc Lộ", "玉露"),
    "yunwu": (H, "Vân Vụ", "云雾"),
    "yuqian": (H, "Vũ Tiền", "雨前 (hái trước tiết Cốc Vũ)"),
    "zhili": (H, "Chức Lý", "织里"),
    "zhoushan": (H, "Chu Sơn", "舟山"),
    "zibo": (H, "Truy Bác", "淄博"),
    "xiaochong": (H, "Tiểu Chủng", "小种 (phiên sai)"),
    # ---- MT left a common word as pinyin / wrong reading -> real Vietnamese word
    "luzhou": (C, "hương đậm", "Luzhou hương vị => hương đậm ; Luzhou Fragrant Tea => trà hương đậm", "MT hiểu nhầm 浓香型 (hương đậm) thành rượu Lô Châu"),
    "agan": (T, "Forrest Gump", "阿甘鞋; thống nhất với các dòng đã ghi 'giày Forrest Gump'"),
    "daquan": (T, "đủ loại", "大全 = trọn bộ/đủ loại, không phải tên riêng"),
    "xiaoxiang": (T, "Chanel", "小香风 = phong cách Chanel"),
    "xiaoxiangfeng": (T, "phong cách Chanel", "小香风"),
    "lanjing": (T, "Lenzing", "兰精 = hãng sợi Lenzing (Tencel), thống nhất với dòng ghi 'Tencel Lenzing'"),
    "lingge": (T, "trần trám", "菱格 = họa tiết trần trám"),
    "maodu": (T, "lá sách", "毛肚 = lá sách bò"),
    "banya": (T, "vịt ép", "板鸭 (vịt muối ép, đặc sản Nam Kinh)"),
    "gaoshan": (T, "núi cao", "高山"),
    "mingtai": (T, "minh thái", "明太 = cá minh thái"),
    "pixiu": (T, "tỳ hưu", "貔貅"),
    "xiangsi": (T, "tương tư", "相思 (gỗ tương tư)"),
    "jixuecao": (T, "rau má", "积雪草"),
    "luoshen": (T, "atiso đỏ", "洛神花 = hoa atiso đỏ / bụp giấm"),
    "maixiang": (T, "hương lúa mạch", "麦香"),
    "nezha": (T, "Na Tra", "哪吒"),
    "taiju": (T, "cúc nụ", "胎菊"),
    "tengjiao": (T, "tiêu xanh", "藤椒"),
    "yuzhu": (T, "ngọc trúc", "玉竹 (vị thuốc)"),
    "zicao": (T, "tử thảo", "紫草"),
    "laicai": (T, "chiêu tài", "来财"),
    "remaji": (T, "Thermage", "热玛吉 = công nghệ Thermage"),
    "kapibala": (T, "capybara", "卡皮巴拉"),
    "pindou": (T, "hạt ghép hình", "拼豆 (perler beads)"),
    "tanabata": (T, "Thất Tịch", "七夕 bị dịch qua tiếng Nhật"),
    "linen": (T, "lanh", "'cotton linen' -> 'cotton lanh' (Tiki gần như không dùng 'linen')"),
    "pique": (T, "cá sấu", "vải pique = vải cá sấu"),
    "angelica": (T, "đương quy", "当归"),
    # ---- only right as a whole name
    "jin": (C, "", "Jin Jun Mei => Kim Tuấn Mi ; Jin Junmei => Kim Tuấn Mi", "Còn lại là tên hãng (Jin Anda...) -> giữ"),
    "jun": (C, "", "Jin Jun Mei => Kim Tuấn Mi", ""),
    "mei": (C, "", "Jin Jun Mei => Kim Tuấn Mi", "Còn lại là tên hãng (Mei Ti Xiu, Mei Dailin) -> giữ"),
    "souchong": (C, "Tiểu Chủng", "Lapsang Souchong => Chính Sơn Tiểu Chủng ; Zhengshan Souchong => Chính Sơn Tiểu Chủng", ""),
    "lapsang": (C, "", "Lapsang Souchong => Chính Sơn Tiểu Chủng", ""),
    "dahai": (C, "", "Fat Dahai => bàng đại hải ; Pang Da Hai => bàng đại hải", "胖大海"),
    "lusi": (C, "", "Zhao Lusi => Triệu Lộ Tư", "赵露思"),
    "yibo": (C, "", "Wang Yibo => Vương Nhất Bác", "王一博"),
    "mountain": (C, "", "Wuyi Mountain => núi Vũ Di ; High Mountain => núi cao", ""),
    "cake": (C, "", "White Tea Cake => bánh trà trắng ; Tea Cake => bánh trà", ""),
    "base": (C, "", "Base Layer => áo lót giữ nhiệt", ""),
    "late": (C, "", "Stay Up Late Mask => mặt nạ thức khuya", ""),
    "leisure": (C, "", "Leisure Snack => đồ ăn vặt", ""),
    "human": (C, "", "Human Skin Glowing Mask => mặt nạ da căng bóng", ""),
    "sausage": (C, "", "Codfish Sausage => xúc xích cá tuyết", ""),
    # ---- undecided
    "fude": (X, "", "Có thể là 福鼎 Phúc Đỉnh bị phiên sai; 'Chen Fude' không rõ"),
    "buzhou": (X, "", "Không dò ra chữ Hán"),
    "american": (X, "", "冰美式 = cà phê Americano đá; 'Ice American' là tên mặt nạ"),
    "sunshine": (X, "", "'Deep Valley Sunshine' tên trà, không rõ nguyên văn"),
    "warehouse": (X, "", "'Lightning Warehouse' có thể là tên hãng"),
    "olitide": (X, "", "Không rõ (có thể là oligopeptide)"),
    "gaiwan": (X, "", "盖碗 = bát trà có nắp; 'Trà Gaiwan' không rõ nghĩa"),
    "gantou": (X, "", "Không dò ra chữ Hán"),
    "mala": (X, "", "'mala Tang' = 麻辣烫?"),
    "songtou": (X, "", "Không rõ"),
    "xiaochongbi": (X, "", "Có thể dính 'Xiaochong' + 'Bi(luochun)'"),
    "xiaosa": (X, "", "Có thể là 小种 phiên sai"),
    "xiaozheng": (X, "", "消正? không rõ"),
    "yanzikuo": (X, "", "Không dò ra chữ Hán"),
    "yuxiang": (X, "", "Không dò ra chữ Hán"),
    "xuecao": (X, "", "'Centella Xuecao' = 积雪草 bị tách đôi; nên gộp thành 'rau má'"),
    "zhengwei": (X, "", "正味 = vị truyền thống, hay tên hãng?"),
    "adian": (X, "", "'axit adian' không rõ"),
    "line": (X, "", "'Free Line' không rõ"),
    "boutique": (X, "", "Không rõ"),
}
DEC.pop("tongmuguan_", None)

NOTE_GIU = {
    "tongrentang": "Tên hãng; VN hay gọi Đồng Nhân Đường, anh cân nhắc",
    "xiaohongshu": "Tên nền tảng (Tiểu Hồng Thư), giữ như Douyin",
    "kuaishou": "Tên nền tảng",
    "shaqima": "Tên bánh, người bán VN viết 'Sachima'",
    "sachima": "Tên bánh",
    "hongqi": "Hãng xe Hồng Kỳ, VN gọi Hongqi",
    "lanka": "Trong 'Sri Lanka'",
}
